import { IStaff } from "../types/types";

export const iStaff: IStaff =  {
  _id: '',
  firstname: '',
  middlename: '',
  lastname: '',
  department: '',
  timestamp: '',
  createdPwd: false,
  staffID: '',
  phone: '',
  username: '',
  dob:'',
  email: '',
  title: '',
  admin: false,
  superUser: false,
  image: '',
  courses: [],
  gender: '',
  dept: '',
  active: true,
  residentialAddress: '',
}